// Code generated by protoc-gen-go. DO NOT EDIT.
// source: networkservice.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Graph struct {
	Nodes                map[int64]*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Graph) Reset()         { *m = Graph{} }
func (m *Graph) String() string { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()    {}
func (*Graph) Descriptor() ([]byte, []int) {
	return fileDescriptor_361e8247d5a9945c, []int{0}
}

func (m *Graph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Graph.Unmarshal(m, b)
}
func (m *Graph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Graph.Marshal(b, m, deterministic)
}
func (m *Graph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph.Merge(m, src)
}
func (m *Graph) XXX_Size() int {
	return xxx_messageInfo_Graph.Size(m)
}
func (m *Graph) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph.DiscardUnknown(m)
}

var xxx_messageInfo_Graph proto.InternalMessageInfo

func (m *Graph) GetNodes() map[int64]*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Neighbors            map[int64]bool `protobuf:"bytes,2,rep,name=neighbors,proto3" json:"neighbors,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_361e8247d5a9945c, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetNeighbors() map[int64]bool {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

type AddGraphRequest struct {
	Graph                *Graph   `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGraphRequest) Reset()         { *m = AddGraphRequest{} }
func (m *AddGraphRequest) String() string { return proto.CompactTextString(m) }
func (*AddGraphRequest) ProtoMessage()    {}
func (*AddGraphRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_361e8247d5a9945c, []int{2}
}

func (m *AddGraphRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGraphRequest.Unmarshal(m, b)
}
func (m *AddGraphRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGraphRequest.Marshal(b, m, deterministic)
}
func (m *AddGraphRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGraphRequest.Merge(m, src)
}
func (m *AddGraphRequest) XXX_Size() int {
	return xxx_messageInfo_AddGraphRequest.Size(m)
}
func (m *AddGraphRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGraphRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddGraphRequest proto.InternalMessageInfo

func (m *AddGraphRequest) GetGraph() *Graph {
	if m != nil {
		return m.Graph
	}
	return nil
}

type AddGraphResponse struct {
	GraphId              int64    `protobuf:"varint,1,opt,name=graphId,proto3" json:"graphId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGraphResponse) Reset()         { *m = AddGraphResponse{} }
func (m *AddGraphResponse) String() string { return proto.CompactTextString(m) }
func (*AddGraphResponse) ProtoMessage()    {}
func (*AddGraphResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_361e8247d5a9945c, []int{3}
}

func (m *AddGraphResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGraphResponse.Unmarshal(m, b)
}
func (m *AddGraphResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGraphResponse.Marshal(b, m, deterministic)
}
func (m *AddGraphResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGraphResponse.Merge(m, src)
}
func (m *AddGraphResponse) XXX_Size() int {
	return xxx_messageInfo_AddGraphResponse.Size(m)
}
func (m *AddGraphResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGraphResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddGraphResponse proto.InternalMessageInfo

func (m *AddGraphResponse) GetGraphId() int64 {
	if m != nil {
		return m.GraphId
	}
	return 0
}

type DeleteGraphRequest struct {
	GraphId              int64    `protobuf:"varint,1,opt,name=graphId,proto3" json:"graphId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGraphRequest) Reset()         { *m = DeleteGraphRequest{} }
func (m *DeleteGraphRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGraphRequest) ProtoMessage()    {}
func (*DeleteGraphRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_361e8247d5a9945c, []int{4}
}

func (m *DeleteGraphRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGraphRequest.Unmarshal(m, b)
}
func (m *DeleteGraphRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGraphRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGraphRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGraphRequest.Merge(m, src)
}
func (m *DeleteGraphRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGraphRequest.Size(m)
}
func (m *DeleteGraphRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGraphRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGraphRequest proto.InternalMessageInfo

func (m *DeleteGraphRequest) GetGraphId() int64 {
	if m != nil {
		return m.GraphId
	}
	return 0
}

type ShortestPathRequest struct {
	GraphId              int64    `protobuf:"varint,1,opt,name=graphId,proto3" json:"graphId,omitempty"`
	SourceNodeId         int64    `protobuf:"varint,2,opt,name=sourceNodeId,proto3" json:"sourceNodeId,omitempty"`
	DestNodeId           int64    `protobuf:"varint,3,opt,name=destNodeId,proto3" json:"destNodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortestPathRequest) Reset()         { *m = ShortestPathRequest{} }
func (m *ShortestPathRequest) String() string { return proto.CompactTextString(m) }
func (*ShortestPathRequest) ProtoMessage()    {}
func (*ShortestPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_361e8247d5a9945c, []int{5}
}

func (m *ShortestPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortestPathRequest.Unmarshal(m, b)
}
func (m *ShortestPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortestPathRequest.Marshal(b, m, deterministic)
}
func (m *ShortestPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortestPathRequest.Merge(m, src)
}
func (m *ShortestPathRequest) XXX_Size() int {
	return xxx_messageInfo_ShortestPathRequest.Size(m)
}
func (m *ShortestPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortestPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShortestPathRequest proto.InternalMessageInfo

func (m *ShortestPathRequest) GetGraphId() int64 {
	if m != nil {
		return m.GraphId
	}
	return 0
}

func (m *ShortestPathRequest) GetSourceNodeId() int64 {
	if m != nil {
		return m.SourceNodeId
	}
	return 0
}

func (m *ShortestPathRequest) GetDestNodeId() int64 {
	if m != nil {
		return m.DestNodeId
	}
	return 0
}

type ShortestPathResponse struct {
	Distance             int64    `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortestPathResponse) Reset()         { *m = ShortestPathResponse{} }
func (m *ShortestPathResponse) String() string { return proto.CompactTextString(m) }
func (*ShortestPathResponse) ProtoMessage()    {}
func (*ShortestPathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_361e8247d5a9945c, []int{6}
}

func (m *ShortestPathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortestPathResponse.Unmarshal(m, b)
}
func (m *ShortestPathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortestPathResponse.Marshal(b, m, deterministic)
}
func (m *ShortestPathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortestPathResponse.Merge(m, src)
}
func (m *ShortestPathResponse) XXX_Size() int {
	return xxx_messageInfo_ShortestPathResponse.Size(m)
}
func (m *ShortestPathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortestPathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShortestPathResponse proto.InternalMessageInfo

func (m *ShortestPathResponse) GetDistance() int64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func init() {
	proto.RegisterType((*Graph)(nil), "proto.Graph")
	proto.RegisterMapType((map[int64]*Node)(nil), "proto.Graph.NodesEntry")
	proto.RegisterType((*Node)(nil), "proto.Node")
	proto.RegisterMapType((map[int64]bool)(nil), "proto.Node.NeighborsEntry")
	proto.RegisterType((*AddGraphRequest)(nil), "proto.AddGraphRequest")
	proto.RegisterType((*AddGraphResponse)(nil), "proto.AddGraphResponse")
	proto.RegisterType((*DeleteGraphRequest)(nil), "proto.DeleteGraphRequest")
	proto.RegisterType((*ShortestPathRequest)(nil), "proto.ShortestPathRequest")
	proto.RegisterType((*ShortestPathResponse)(nil), "proto.ShortestPathResponse")
}

func init() { proto.RegisterFile("networkservice.proto", fileDescriptor_361e8247d5a9945c) }

var fileDescriptor_361e8247d5a9945c = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x6d, 0x0c, 0x61, 0x1c, 0x95, 0x6a, 0x88, 0x5a, 0xb3, 0x95, 0x50, 0xd8, 0x53, 0x0e,
	0xb0, 0x95, 0x8c, 0x90, 0x2a, 0x04, 0x07, 0x10, 0x11, 0xca, 0xa5, 0x42, 0xee, 0x17, 0x24, 0xd9,
	0x21, 0xb1, 0x1a, 0xbc, 0x61, 0x77, 0x53, 0x94, 0x03, 0xbf, 0xc0, 0x27, 0xf2, 0x2d, 0x68, 0x77,
	0x6d, 0xe2, 0xd0, 0xa0, 0x9e, 0xec, 0x99, 0xf7, 0x76, 0xe6, 0xcd, 0xd3, 0x83, 0x41, 0x4d, 0xf6,
	0x87, 0xd2, 0x37, 0x86, 0xf4, 0x6d, 0x35, 0x27, 0xb1, 0xd6, 0xca, 0x2a, 0x4c, 0xfd, 0x87, 0x9d,
	0x2f, 0x94, 0x5a, 0xac, 0xe8, 0xc2, 0x57, 0xb3, 0xcd, 0xd7, 0x0b, 0xfa, 0xb6, 0xb6, 0xdb, 0xc0,
	0xe1, 0x3f, 0x21, 0xfd, 0xac, 0xa7, 0xeb, 0x25, 0xbe, 0x82, 0xb4, 0x56, 0x92, 0x4c, 0x1e, 0x0d,
	0x93, 0x51, 0x56, 0x9c, 0x05, 0x5c, 0x78, 0x50, 0x5c, 0x39, 0x64, 0x5c, 0x5b, 0xbd, 0x2d, 0x03,
	0x8b, 0x8d, 0x01, 0x76, 0x4d, 0x3c, 0x81, 0xe4, 0x86, 0xb6, 0x79, 0x34, 0x8c, 0x46, 0x49, 0xe9,
	0x7e, 0xf1, 0x05, 0xa4, 0xb7, 0xd3, 0xd5, 0x86, 0xf2, 0x78, 0x18, 0x8d, 0xb2, 0x22, 0x6b, 0xc6,
	0xb9, 0x37, 0x65, 0x40, 0xde, 0xc6, 0x97, 0x11, 0xff, 0x15, 0xc1, 0x03, 0xd7, 0xc3, 0x63, 0x88,
	0x2b, 0xd9, 0x0c, 0x88, 0x2b, 0x89, 0x97, 0xf0, 0xb8, 0xa6, 0x6a, 0xb1, 0x9c, 0x29, 0x6d, 0xf2,
	0xd8, 0x4b, 0x62, 0x9d, 0x19, 0xe2, 0xaa, 0x05, 0x83, 0xaa, 0x1d, 0x99, 0xbd, 0x83, 0xe3, 0x7d,
	0xf0, 0x80, 0xba, 0x41, 0x57, 0x5d, 0xaf, 0x2b, 0xe8, 0x0d, 0x3c, 0xf9, 0x20, 0xa5, 0xbf, 0xba,
	0xa4, 0xef, 0x1b, 0x32, 0x16, 0x39, 0xa4, 0x0b, 0x57, 0xfb, 0x01, 0x59, 0xd1, 0xef, 0x3a, 0x53,
	0x06, 0x88, 0xbf, 0x84, 0x93, 0xdd, 0x33, 0xb3, 0x56, 0xb5, 0x21, 0xcc, 0xe1, 0x91, 0x07, 0x27,
	0xed, 0x5d, 0x6d, 0xc9, 0x05, 0xe0, 0x27, 0x5a, 0x91, 0xa5, 0xbd, 0x3d, 0xff, 0xe7, 0x1b, 0x78,
	0x7a, 0xbd, 0x54, 0xda, 0x92, 0xb1, 0x5f, 0xa6, 0xf6, 0xfe, 0x07, 0xc8, 0xa1, 0x6f, 0xd4, 0x46,
	0xcf, 0xc9, 0x79, 0x35, 0x91, 0xfe, 0xcc, 0xa4, 0xdc, 0xeb, 0xe1, 0x73, 0x00, 0x49, 0xc6, 0x36,
	0x8c, 0xc4, 0x33, 0x3a, 0x1d, 0x5e, 0xc0, 0x60, 0x7f, 0x69, 0x73, 0x16, 0x83, 0x9e, 0xac, 0x8c,
	0x9d, 0xd6, 0x73, 0x6a, 0xd6, 0xfe, 0xad, 0x8b, 0xdf, 0x91, 0x33, 0xdf, 0x47, 0xf1, 0x3a, 0x44,
	0x11, 0xdf, 0x43, 0xaf, 0x75, 0x06, 0x4f, 0x1b, 0xeb, 0xfe, 0x71, 0x98, 0x9d, 0xdd, 0xe9, 0x87,
	0x5d, 0xfc, 0x08, 0x3f, 0x42, 0xd6, 0xb1, 0x0a, 0x9f, 0x35, 0xcc, 0xbb, 0xf6, 0xb1, 0x53, 0x11,
	0x72, 0x2e, 0xda, 0x9c, 0x8b, 0xb1, 0xcb, 0x39, 0x3f, 0xc2, 0x09, 0xf4, 0xbb, 0x97, 0x60, 0x1b,
	0xa4, 0x03, 0x9e, 0xb2, 0xf3, 0x83, 0x58, 0x2b, 0x67, 0xf6, 0xd0, 0xa3, 0xaf, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x87, 0xd0, 0x70, 0x79, 0x71, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NetworkServiceClient is the client API for NetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkServiceClient interface {
	AddGraph(ctx context.Context, in *AddGraphRequest, opts ...grpc.CallOption) (*AddGraphResponse, error)
	DeleteGraph(ctx context.Context, in *DeleteGraphRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ShortestPath(ctx context.Context, in *ShortestPathRequest, opts ...grpc.CallOption) (*ShortestPathResponse, error)
}

type networkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkServiceClient(cc grpc.ClientConnInterface) NetworkServiceClient {
	return &networkServiceClient{cc}
}

func (c *networkServiceClient) AddGraph(ctx context.Context, in *AddGraphRequest, opts ...grpc.CallOption) (*AddGraphResponse, error) {
	out := new(AddGraphResponse)
	err := c.cc.Invoke(ctx, "/proto.NetworkService/AddGraph", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) DeleteGraph(ctx context.Context, in *DeleteGraphRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.NetworkService/DeleteGraph", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) ShortestPath(ctx context.Context, in *ShortestPathRequest, opts ...grpc.CallOption) (*ShortestPathResponse, error) {
	out := new(ShortestPathResponse)
	err := c.cc.Invoke(ctx, "/proto.NetworkService/ShortestPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServiceServer is the server API for NetworkService service.
type NetworkServiceServer interface {
	AddGraph(context.Context, *AddGraphRequest) (*AddGraphResponse, error)
	DeleteGraph(context.Context, *DeleteGraphRequest) (*empty.Empty, error)
	ShortestPath(context.Context, *ShortestPathRequest) (*ShortestPathResponse, error)
}

// UnimplementedNetworkServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNetworkServiceServer struct {
}

func (*UnimplementedNetworkServiceServer) AddGraph(ctx context.Context, req *AddGraphRequest) (*AddGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGraph not implemented")
}
func (*UnimplementedNetworkServiceServer) DeleteGraph(ctx context.Context, req *DeleteGraphRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGraph not implemented")
}
func (*UnimplementedNetworkServiceServer) ShortestPath(ctx context.Context, req *ShortestPathRequest) (*ShortestPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShortestPath not implemented")
}

func RegisterNetworkServiceServer(s *grpc.Server, srv NetworkServiceServer) {
	s.RegisterService(&_NetworkService_serviceDesc, srv)
}

func _NetworkService_AddGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).AddGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NetworkService/AddGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).AddGraph(ctx, req.(*AddGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_DeleteGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).DeleteGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NetworkService/DeleteGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).DeleteGraph(ctx, req.(*DeleteGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_ShortestPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortestPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).ShortestPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NetworkService/ShortestPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).ShortestPath(ctx, req.(*ShortestPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NetworkService",
	HandlerType: (*NetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGraph",
			Handler:    _NetworkService_AddGraph_Handler,
		},
		{
			MethodName: "DeleteGraph",
			Handler:    _NetworkService_DeleteGraph_Handler,
		},
		{
			MethodName: "ShortestPath",
			Handler:    _NetworkService_ShortestPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "networkservice.proto",
}
